-- Migration 013: conversations, outreach_sequences, activity_log
--
-- These tables are referenced by outreach, reply-classification, meeting-prep,
-- approval-queue, clients-manager, advertising, social-engagement,
-- core/health-scoring, and core/renewal. They were missing from the schema,
-- causing silent failures (Supabase errors go unchecked in most call sites).

-- ─────────────────────────────────────────────────────────────────────
-- outreach_sequences
-- Written by outreach agent. Represents a planned multi-step campaign
-- for a given lead/contact.
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS outreach_sequences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  lead_id UUID REFERENCES leads(id) ON DELETE SET NULL,
  contact_id UUID REFERENCES contacts(id) ON DELETE SET NULL,
  sequence_name TEXT,
  sequence_type TEXT DEFAULT 'multi_channel',
  sequence_status TEXT DEFAULT 'draft',
  step_number INTEGER DEFAULT 1,
  message_subject TEXT,
  message_body TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_outreach_sequences_tenant ON outreach_sequences(tenant_id);
CREATE INDEX IF NOT EXISTS idx_outreach_sequences_lead ON outreach_sequences(lead_id);

ALTER TABLE outreach_sequences ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_iso_outreach_sequences ON outreach_sequences FOR ALL
  USING (tenant_id = current_setting('app.tenant_id', true)::uuid);

-- ─────────────────────────────────────────────────────────────────────
-- conversations
-- Multi-channel threaded communications (email, sms, linkedin, phone).
-- Distinct from `messages` which is the transport-level log.
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  lead_id UUID REFERENCES leads(id) ON DELETE SET NULL,
  contact_id UUID REFERENCES contacts(id) ON DELETE SET NULL,
  sequence_id UUID REFERENCES outreach_sequences(id) ON DELETE SET NULL,
  channel TEXT NOT NULL,
  direction TEXT NOT NULL DEFAULT 'outbound',
  message_subject TEXT,
  message_body TEXT,
  ai_classification TEXT,
  sentiment TEXT,
  external_id TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_conversations_tenant ON conversations(tenant_id);
CREATE INDEX IF NOT EXISTS idx_conversations_lead ON conversations(lead_id);
CREATE INDEX IF NOT EXISTS idx_conversations_unclassified
  ON conversations(tenant_id, direction, created_at)
  WHERE ai_classification IS NULL;

ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_iso_conversations ON conversations FOR ALL
  USING (tenant_id = current_setting('app.tenant_id', true)::uuid);

-- ─────────────────────────────────────────────────────────────────────
-- activity_log
-- General-purpose activity log (distinct from agent_activity_log which
-- logs agent job lifecycle). Used by agents to record business-level
-- events — lead classified, client health alert, email sent, etc.
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS activity_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  agent TEXT,
  action TEXT NOT NULL,
  entity_type TEXT,
  entity_id UUID,
  level TEXT DEFAULT 'info',
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_activity_log_tenant ON activity_log(tenant_id, created_at);
CREATE INDEX IF NOT EXISTS idx_activity_log_agent ON activity_log(tenant_id, agent, created_at);

ALTER TABLE activity_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_iso_activity_log ON activity_log FOR ALL
  USING (tenant_id = current_setting('app.tenant_id', true)::uuid);

-- ─────────────────────────────────────────────────────────────────────
-- meeting_briefings
-- Stores Claude-generated briefings generated by meeting-prep agent.
-- Also adds briefing_generated flag on leads so the agent can skip
-- leads that already have a briefing.
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS meeting_briefings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  lead_id UUID REFERENCES leads(id) ON DELETE CASCADE,
  briefing_data JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_meeting_briefings_tenant ON meeting_briefings(tenant_id);
CREATE INDEX IF NOT EXISTS idx_meeting_briefings_lead ON meeting_briefings(lead_id);

ALTER TABLE meeting_briefings ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_iso_meeting_briefings ON meeting_briefings FOR ALL
  USING (tenant_id = current_setting('app.tenant_id', true)::uuid);

ALTER TABLE leads ADD COLUMN IF NOT EXISTS briefing_generated BOOLEAN DEFAULT FALSE;

-- ─────────────────────────────────────────────────────────────────────
-- marketing_performance_reports
-- Stores weekly ad-performance analyses generated by advertising agent.
-- ─────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS marketing_performance_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  report_data JSONB NOT NULL DEFAULT '{}',
  metrics JSONB DEFAULT '{}',
  period_days INTEGER DEFAULT 30,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mkt_perf_reports_tenant ON marketing_performance_reports(tenant_id, created_at);

ALTER TABLE marketing_performance_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_iso_mkt_perf_reports ON marketing_performance_reports FOR ALL
  USING (tenant_id = current_setting('app.tenant_id', true)::uuid);
