'use strict';

/**
 * The wizard write path, which was an arbitrary config-write primitive.
 *
 * FOUND BY REVIEW, 2026-08-02. POST /api/tenant/onboarding-step wrote
 * `Object.entries(data)` straight into tenant_config with no allow-list. An
 * authenticated tenant could:
 *
 *   • POST {step:'agreement', data:{}} and have the service terms recorded as
 *     accepted with no signature, no acceptance and no versions;
 *   • POST data.onboarding_steps_completed with every step and skip the wizard
 *     entirely, because the handler re-reads that key immediately afterwards;
 *   • overwrite ANY tenant_config key — telnyx_phone_number, owner_email,
 *     preflight_passed_at, wizard_excluded_steps.
 *
 * The resolver's refusal to exclude `agreement` was worthless while this
 * endpoint would mark it complete for you. A guarded door in a missing wall.
 *
 * The suite was fully green throughout, which is why these tests exist: they
 * assert what the endpoint must REFUSE, not what it accepts.
 */

const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const path = require('path');

const SRC = fs.readFileSync(
  path.join(__dirname, '..', 'api', 'routes', 'tenant.js'), 'utf8',
);

/** Pull the frozen allow-list out of the route module without booting it. */
function writableFields() {
  const m = SRC.match(/const WIZARD_WRITABLE_FIELDS = Object\.freeze\((\{[\s\S]*?\n\}\))/);
  assert.ok(m, 'WIZARD_WRITABLE_FIELDS must exist — it is the allow-list');
  // eslint-disable-next-line no-eval
  return eval(`(${m[1]}`);
}

test('the write path has an allow-list at all', () => {
  const fields = writableFields();
  assert.ok(Object.keys(fields).length > 10, 'every wizard step needs an entry');
  assert.match(SRC, /const allowed = new Set\(WIZARD_WRITABLE_FIELDS\[step\]/);
  assert.match(SRC, /rejected\.length/, 'unknown fields must be rejected, not ignored');

  // Ordering is the whole thing: the filter has to run BEFORE the write.
  // Object.entries(stepData) still appears — that is the upsert of the
  // already-filtered data — so what matters is which comes first.
  const gate  = SRC.indexOf('const rejected = Object.keys(stepData)');
  const write = SRC.indexOf('const upserts = Object.entries(stepData)');
  assert.ok(gate > 0 && write > 0, 'both the gate and the write must exist');
  assert.ok(gate < write,
    'the allow-list check must run before anything is written to tenant_config');
});

test('NO step may write the completion record', () => {
  // This is the wizard-skip. The handler re-reads onboarding_steps_completed
  // right after writing the caller's data, so accepting it let someone declare
  // the whole wizard finished in one request.
  const fields = writableFields();
  for (const [step, keys] of Object.entries(fields)) {
    assert.ok(!keys.includes('onboarding_steps_completed'),
      `${step} must not be able to write the completion record`);
  }
});

test('no step may write another step\'s fields', () => {
  const fields = writableFields();
  // The logo step must not be able to set the phone number, and so on.
  assert.ok(!fields.logo.includes('telnyx_phone_number'));
  assert.ok(!fields.logo.includes('owner_email'));
  assert.ok(!fields.colors.includes('agreement_signature'));
  // Nothing may write the operator's own controls.
  for (const [step, keys] of Object.entries(fields)) {
    for (const forbidden of ['wizard_excluded_steps', 'preflight_passed_at',
      'onboarding_stage', 'telnyx_phone_number', 'owner_email', 'tier']) {
      assert.ok(!keys.includes(forbidden), `${step} must not write ${forbidden}`);
    }
  }
});

test('the agreement cannot be accepted without a signature and versions', () => {
  // An empty body used to be enough.
  assert.match(SRC, /A typed signature is required to accept the agreement/);
  assert.match(SRC, /must record which document versions were accepted/);
});

test('consent evidence is generated by the SERVER, not the browser', () => {
  // agreement_accepted_at came from `new Date()` in the customer's browser,
  // and agreement_acceptance_ip was documented but never written at all.
  assert.match(SRC, /stepData\.agreement_accepted_at = new Date\(\)\.toISOString\(\)/,
    'the acceptance time must be the server clock');
  assert.match(SRC, /stepData\.agreement_acceptance_ip =/,
    'the acceptance IP must be observed by the server');
  assert.match(SRC, /x-forwarded-for/, 'and read through the proxy header');
});

test('completion verifies the evidence exists, not just the step name', () => {
  // The completion endpoint checked only that 'agreement' appeared in a list
  // of strings — a claim, not evidence.
  assert.match(SRC, /agreement_signature\) missingEvidence\.push/);
  assert.match(SRC, /agreement_acceptance_ip\) missingEvidence\.push/);
  assert.match(SRC, /is not properly accepted/);
});

test('the allow-list covers every step the resolver can show', () => {
  // A step the wizard can render but the allow-list does not know about would
  // reject every field and strand the customer on it.
  const { STEP_DEFINITIONS } = require('../core/onboarding-step-resolver');
  const fields = writableFields();
  for (const d of STEP_DEFINITIONS) {
    assert.ok(Object.prototype.hasOwnProperty.call(fields, d.key),
      `step "${d.key}" can be shown but has no allow-list entry — the customer `
      + 'would be unable to complete it');
  }
});

test('the allow-list matches what the wizard actually sends', () => {
  // Drift here strands the customer: the UI posts a field the API rejects.
  // These are the field names read out of the step components.
  const fields = writableFields();
  const REAL = {
    logo: ['logo_url'],
    colors: ['color_primary', 'color_secondary'],
    voice: ['brand_voice'],
    photos: ['photo_seed_urls', 'photo_seed_count'],
    customers: ['customers_imported_count'],
    social: ['facebook_url', 'instagram_url'],
    gbp: ['google_review_url', 'gbp_status'],
    path_choice: ['delivery_path'],
    apple_details: ['legal_entity_name', 'duns_number'],
    agreement: ['agreement_signature', 'agreement_versions', 'agreement_dpa_accepted'],
  };
  for (const [step, keys] of Object.entries(REAL)) {
    for (const k of keys) {
      assert.ok(fields[step].includes(k),
        `the wizard posts ${k} on "${step}" but the API would reject it`);
    }
  }
});
