/**
 * Growth OS — Follow-Up Agent
 * Sends multi-step SMS follow-up sequences to leads that haven't responded.
 *
 * Scheduled: hourly during business hours (8am-6pm weekdays)
 * Uses contacts.drip_stage to track position in sequence.
 * Respects configurable follow_up_steps and spacing.
 */

const { createLogger } = require('../../core/logger');
const { getConfig } = require('../../core/config');
const { db } = require('../../db/client');
const { sendSms, SmsCapExceededError } = require('../../integrations/twilio');
const { sendEmail } = require('../../integrations/email');
const { checkIdempotency, recordIdempotency } = require('../../db/queries/jobs');
const { claudeHaiku } = require('../../integrations/claude');

/**
 * Render SMS template with lead/contact data
 */
function renderTemplate(template, lead, tenant) {
  const businessName = getConfig(tenant, 'business_name', tenant.name || 'Our Team');
  return template
    .replace(/{name}/g, lead.name || 'there')
    .replace(/{business_name}/g, businessName)
    .replace(/{service_type}/g, lead.service_type || 'your needs');
}

/**
 * AI-personalized follow-up SMS for a specific step in the cadence.
 * Module 4.3 + 4.4: each message generated by AI in the tenant's brand
 * voice, referencing the specific service the prospect asked about,
 * the estimate amount (if any), and how long it's been since the last
 * touch. Falls back to the static template on failure so follow-ups
 * never fail to send.
 */
async function generatePersonalizedFollowUp(tenant, lead, step, maxSteps, lastContactedAt, fallbackTemplate, log) {
  const businessName = getConfig(tenant, 'business_name', tenant.name || 'Our Team');
  const brandVoice = getConfig(tenant, 'brand_voice', 'Friendly, professional, no-nonsense. Sounds like a real person.');

  const daysSinceLast = lastContactedAt
    ? Math.max(0, Math.floor((Date.now() - new Date(lastContactedAt).getTime()) / (1000 * 60 * 60 * 24)))
    : null;

  const stepIntent = step === 1
    ? 'soft check-in — gentle "any questions?" energy'
    : step === maxSteps
    ? 'final touch — direct but not desperate, give a clear path to say yes OR opt out'
    : 'mid-cadence nudge — offer a specific reason to act this week';

  const systemPrompt = `You are writing follow-up SMS #${step} of ${maxSteps} for ${businessName} to a customer who contacted us and hasn't replied yet. Brand voice: ${brandVoice}

Intent of this specific message: ${stepIntent}

Rules:
- Output ONLY the SMS body. No quotes around it.
- 25-50 words MAX.
- Reference the customer's first name once if you have it.
- ONLY reference a quote, estimate, or specific service if the "Estimate quoted" field is provided. Do NOT invent or assume any quote, estimate, or prior conversation that isn't in the context.
- If no estimate is provided, keep it general — ask if they still need help or have questions.
- ${daysSinceLast != null ? `It's been ~${daysSinceLast} days since the last message — acknowledge time has passed but don't be needy.` : 'Treat as first follow-up since initial contact.'}
- End with a clear, low-pressure next step.
- No signature, no business name sign-off.
- No "Reply STOP to unsubscribe" — that gets appended elsewhere.`;

  const firstName = (lead.name || '').split(/\s+/)[0] || '';
  const context = [
    `Our company: ${businessName} (we sell a done-for-you business operating system to small businesses)`,
    `Prospect: ${firstName || '(no name)'}`,
    lead.service_type ? `Prospect's industry: ${lead.service_type} (this is THEIR business, not ours)` : null,
    lead.estimate_amount ? `Estimate quoted: $${lead.estimate_amount}` : null,
    lead.city ? `Prospect's city: ${lead.city}` : null,
  ].filter(Boolean).join('\n');

  const userMessage = `Prospect context:\n${context}\n\nThis is follow-up #${step} of ${maxSteps}. Write the SMS body now.`;

  try {
    const reply = await claudeHaiku(systemPrompt, userMessage, { maxTokens: 220, tenantSlug: tenant.slug });
    const cleaned = String(reply || '').trim().replace(/^["']|["']$/g, '');
    if (!cleaned || cleaned.length < 10 || cleaned.length > 600) {
      log.warn(`Claude returned unusable follow-up body (step ${step}, length=${cleaned.length}), using template`);
      return fallbackTemplate;
    }
    return cleaned;
  } catch (err) {
    log.warn(`Claude personalization failed for follow-up step ${step} (${err.message}), using template fallback`);
    return fallbackTemplate;
  }
}

/**
 * AI-personalized follow-up EMAIL for a step. Longer-form than the SMS —
 * subject + 3-5 sentence body. Falls back to a plain rendering of the SMS
 * body if Claude is unavailable so email follow-ups never silently fail.
 *
 * Module 4.2 sales claim: automated text+email follow-ups on every estimate.
 */
async function generatePersonalizedFollowUpEmail(tenant, lead, step, maxSteps, lastContactedAt, smsBody, log) {
  const businessName = getConfig(tenant, 'business_name', tenant.name || 'Our Team');
  const brandVoice = getConfig(tenant, 'brand_voice', 'Friendly, professional, no-nonsense.');
  const ownerName = getConfig(tenant, 'owner_name', '');

  const daysSinceLast = lastContactedAt
    ? Math.max(0, Math.floor((Date.now() - new Date(lastContactedAt).getTime()) / (1000 * 60 * 60 * 24)))
    : null;

  const stepIntent = step === 1
    ? 'soft check-in'
    : step === maxSteps
    ? 'final touch — direct but not desperate'
    : 'mid-cadence nudge with a concrete reason to act this week';

  const systemPrompt = `You are writing follow-up EMAIL #${step} of ${maxSteps} for ${businessName} to a customer who contacted us and hasn't replied yet. Brand voice: ${brandVoice}

Intent: ${stepIntent}

Return JSON ONLY (no markdown, no commentary) with this exact shape:
{ "subject": "<6-10 words, no quotes>", "body": "<3-5 short sentences, plain text, line breaks OK>" }

Rules for the body:
- Start with the customer's first name once if you have it.
- ONLY reference a quote, estimate, or specific service if the "Estimate quoted" field is provided below. Do NOT invent or assume any quote, estimate, or prior conversation that isn't in the context.
- If no estimate is provided, keep it general — ask if they still need help or have questions.
- ${daysSinceLast != null ? `Acknowledge ~${daysSinceLast} days have passed since the last message.` : 'Treat as first follow-up.'}
- End with one concrete next step (call back, book a time, reply yes/no).
- Sign off with the owner's first name if provided, otherwise the business name.
- No fluffy marketing language. No "Hope this email finds you well."`;

  const firstName = (lead.name || '').split(/\s+/)[0] || '';
  const context = [
    `Our company: ${businessName} (we sell a done-for-you business operating system to small businesses)`,
    `Prospect: ${firstName || '(no name)'}`,
    lead.service_type ? `Prospect's industry: ${lead.service_type} (this is THEIR business, not ours)` : null,
    lead.estimate_amount ? `Estimate quoted: $${lead.estimate_amount}` : null,
    lead.city ? `Prospect's city: ${lead.city}` : null,
    ownerName ? `Sign off as: ${ownerName}` : `Sign off as: ${businessName}`,
  ].filter(Boolean).join('\n');

  const fallback = {
    subject: `Following up — ${businessName}`,
    body: `${firstName ? `Hi ${firstName},` : 'Hi,'}\n\n${smsBody}\n\n${ownerName || businessName}`,
  };

  try {
    const { askClaudeJSON } = require('../../integrations/claude');
    const result = await askClaudeJSON(systemPrompt, `Context:\n${context}\n\nWrite the email.`, {
      maxTokens: 500,
      tenantSlug: tenant.slug,
    });
    if (!result || !result.subject || !result.body) return fallback;
    return {
      subject: String(result.subject).slice(0, 120),
      body: String(result.body).slice(0, 2000),
    };
  } catch (err) {
    log.warn(`Email personalization failed (step ${step}): ${err.message}`);
    return fallback;
  }
}

/**
 * Wrap a plain-text email body into a minimal branded HTML shell so
 * Resend doesn't deliver as a raw text wall. Keeps the body single-column,
 * sans-serif, dark text on white — works in every email client.
 */
function emailBodyToHtml(plainBody, businessName) {
  const escaped = String(plainBody)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
  const paragraphs = escaped
    .split(/\n{2,}/)
    .map((p) => `<p style="margin: 0 0 14px 0;">${p.replace(/\n/g, '<br>')}</p>`)
    .join('');
  return `<!doctype html><html><body style="font-family: -apple-system, Segoe UI, sans-serif; color: #0f172a; max-width: 560px; margin: 0 auto; padding: 24px 16px; line-height: 1.55; font-size: 15px;">${paragraphs}<p style="color: #64748b; font-size: 12px; margin-top: 28px;">Sent on behalf of ${businessName}. Reply to opt out.</p></body></html>`;
}

/**
 * Check if enough time has passed since last contact
 */
function isReadyForFollowUp(lastContactedAt, minHoursBetween) {
  if (!lastContactedAt) return true;
  const hoursSince = (Date.now() - new Date(lastContactedAt).getTime()) / (1000 * 60 * 60);
  return hoursSince >= minHoursBetween;
}

/**
 * @param {Object} tenant - Resolved tenant
 * @param {Object} payload - { limit }
 */
async function run(tenant, payload = {}) {
  const log = createLogger('follow-up', tenant.slug);

  // No Twilio AND no email path → skip quietly. With the email branch
  // added we can still run for email-only tenants (Twilio is optional
  // per-tenant), so only bail when neither channel is available.
  const tw = tenant?.integrations?.twilio;
  const hasTwilio = !!(tw && tw.credentials?.account_sid && tw.config?.phone_number);
  const emailAvailable = !!getConfig(tenant, 'follow_up_email_enabled', true);
  if (!hasTwilio && !emailAvailable) {
    log.info('No Twilio and no email path enabled for this tenant — skipping');
    return { success: true, skipped: true, reason: 'no_send_channel' };
  }

  const maxSteps = Number(getConfig(tenant, 'follow_up_steps', 3));
  const triggerStatus = getConfig(tenant, 'follow_up_trigger_status', 'contacted');
  const hoursBetween = Number(getConfig(tenant, 'follow_up_hours_between', 24));
  const limit = Number(payload.limit || 25);
  const smsTemplates = getConfig(tenant, 'sms_templates', {});

  log.info('Starting follow-up run', { maxSteps, triggerStatus, hoursBetween });

  // Module 4.2 — email channel toggle (defaults ON if a tenant has Resend
  // configured at the platform level; tenants can opt out via config).
  const emailEnabled = !!getConfig(tenant, 'follow_up_email_enabled', true);

  // Find leads in the trigger status. Email-only leads (no phone) are
  // allowed through when emailEnabled — without this they'd be silently
  // dropped. Pull only the contact fields we need.
  //
  // CRITICAL: exclude prospected leads — they never contacted us. Follow-ups
  // saying "checking in on the quote" are fabricated spam. Prospected leads
  // go through the outreach agent which has its own approval-gated cadence.
  const { data: leads, error: leadsErr } = await db
    .from('leads')
    .select('id, name, phone, email, status, lead_source, service_type, city, estimate_amount, contacts(id, is_primary_contact, drip_stage, last_contacted_at, contact_status)')
    .eq('tenant_id', tenant.id)
    .in('status', [triggerStatus, 'contacted', 'estimate_given'])
    .not('lead_source', 'eq', 'prospecting_agent')
    .order('updated_at', { ascending: true })
    .limit(limit);

  if (leadsErr) throw leadsErr;

  if (!leads || leads.length === 0) {
    log.info('No leads due for follow-up');
    return { success: true, sent: 0, skipped: 0, message: 'No leads due for follow-up' };
  }

  let sent = 0;
  let skipped = 0;
  let capReached = false;
  let capInfo = null;
  const processed = [];
  const errors = [];

  for (const lead of leads) {
    if (capReached) {
      skipped++;
      processed.push({ lead_id: lead.id, name: lead.name, action: 'sms_cap_reached' });
      continue;
    }
    try {
      // Never follow up on prospected leads — they didn't contact us.
      if (lead.lead_source === 'prospecting_agent') {
        skipped++;
        processed.push({ lead_id: lead.id, name: lead.name, action: 'prospected_lead_skip' });
        continue;
      }

      // Skip leads with no usable channel at all
      const hasSms = !!lead.phone;
      const hasEmail = emailEnabled && !!lead.email;
      if (!hasSms && !hasEmail) {
        skipped++;
        processed.push({ lead_id: lead.id, name: lead.name, action: 'no_channel' });
        continue;
      }

      // Resolve or create the lead's primary contact so drip_stage has a home.
      // Without this, B2C leads (no contact row) would re-send step 1 every day forever.
      let primaryContact = lead.contacts?.find(c => c.is_primary_contact) || lead.contacts?.[0];

      if (!primaryContact) {
        const { data: created, error: createErr } = await db
          .from('contacts')
          .insert({
            tenant_id: tenant.id,
            lead_id: lead.id,
            name: lead.name || 'Unknown',
            phone: lead.phone,
            email: lead.email,
            is_primary_contact: true,
            drip_stage: 0
          })
          .select('id, is_primary_contact, drip_stage, last_contacted_at')
          .single();

        if (createErr || !created) {
          log.warn('Could not create primary contact; skipping lead', { lead_id: lead.id, err: createErr?.message });
          skipped++;
          processed.push({ lead_id: lead.id, name: lead.name, action: 'contact_create_failed' });
          continue;
        }
        primaryContact = created;
      }

      const currentStage = primaryContact.drip_stage || 0;
      const lastContacted = primaryContact.last_contacted_at || null;

      // Module 4.8 — Stop on reply / opt-out. Reply-classification.js
      // sets contacts.contact_status to 'unsubscribed' when a prospect
      // says STOP / firm_no / unsubscribe. Without this gate, follow-up
      // would keep advancing the cadence and keep texting them — which
      // is both illegal (TCPA opt-out non-compliance) and miserable UX.
      const optedOutStatuses = new Set(['unsubscribed', 'opted_out', 'do_not_contact', 'bounced']);
      if (primaryContact.contact_status && optedOutStatuses.has(primaryContact.contact_status)) {
        skipped++;
        processed.push({ lead_id: lead.id, name: lead.name, action: 'opted_out', contact_status: primaryContact.contact_status });
        continue;
      }
      // Also stop if the lead was won/lost since the cadence started —
      // the deal is decided either way, no point continuing to chase.
      if (lead.status === 'won' || lead.status === 'lost') {
        skipped++;
        processed.push({ lead_id: lead.id, name: lead.name, action: `lead_${lead.status}` });
        continue;
      }

      // Check if we've already completed the sequence
      if (currentStage >= maxSteps) {
        skipped++;
        processed.push({ lead_id: lead.id, name: lead.name, action: 'sequence_complete' });
        continue;
      }

      // Check timing
      if (!isReadyForFollowUp(lastContacted, hoursBetween)) {
        skipped++;
        processed.push({ lead_id: lead.id, name: lead.name, action: 'too_soon' });
        continue;
      }

      // Idempotency — don't send the same step twice in one day
      const today = new Date().toISOString().slice(0, 10);
      const idempKey = `follow-up:${lead.id}:step${currentStage + 1}:${today}`;
      const existing = await checkIdempotency(tenant.id, idempKey);
      if (existing) {
        skipped++;
        processed.push({ lead_id: lead.id, name: lead.name, action: 'already_sent_today' });
        continue;
      }

      // Select the template for this step (used as AI fallback)
      const nextStep = currentStage + 1;
      const templateKey = `follow_up_${nextStep}`;
      const template = smsTemplates[templateKey]
        || `Hi {name}, just following up from {business_name}. Any questions we can answer?`;
      const fallbackBody = renderTemplate(template, lead, tenant);

      // Module 4.3 / 4.4 — AI personalization in tenant voice. Falls
      // back to template if Claude fails.
      const useAi = getConfig(tenant, 'follow_up_use_ai', true);
      const messageBody = useAi
        ? await generatePersonalizedFollowUp(tenant, lead, nextStep, maxSteps, lastContacted, fallbackBody, log)
        : fallbackBody;

      log.info(`Sending follow-up step ${nextStep} to ${lead.name}`, { ai: useAi, sms: hasSms, email: hasEmail });

      // ---- SMS branch (skips if no phone) ----
      let smsResult = null;
      if (hasSms) {
        try {
          smsResult = await sendSms(tenant.integrations, lead.phone, messageBody, {
            tenantSlug: tenant.slug,
            tenant
          });
        } catch (err) {
          if (err instanceof SmsCapExceededError) {
            capReached = true;
            capInfo = { cap: err.cap, count: err.count };
            log.warn(`SMS cap reached (${err.count}/${err.cap}); halting SMS but email branch may still send`);
            // Don't `continue` — if email is available, still send email this step.
          } else {
            throw err;
          }
        }
      }

      if (smsResult) {
        // Log the SMS — both legacy messages table AND lead-scoped
        // conversations so the mobile Lead Detail timeline shows it.
        await db.from('messages').insert({
          tenant_id: tenant.id,
          contact_id: primaryContact?.id || null,
          channel: 'sms',
          direction: 'outbound',
          body: messageBody,
          external_id: smsResult.sid,
          status: 'sent',
          sent_at: new Date().toISOString()
        });
        try {
          await db.from('conversations').insert({
            tenant_id: tenant.id,
            lead_id: lead.id,
            contact_id: primaryContact?.id || null,
            channel: 'sms',
            direction: 'outbound',
            message_body: messageBody,
            metadata: { external_id: smsResult.sid, agent: 'follow-up', step: nextStep, max_steps: maxSteps },
          });
        } catch (convErr) {
          log.warn(`conversations insert failed for follow-up SMS: ${convErr.message}`);
        }
      }

      // ---- Email branch (skips if no email or email disabled) ----
      let emailResult = null;
      if (hasEmail) {
        try {
          const emailMsg = useAi
            ? await generatePersonalizedFollowUpEmail(tenant, lead, nextStep, maxSteps, lastContacted, messageBody, log)
            : { subject: `Following up — ${getConfig(tenant, 'business_name', tenant.name || 'Our Team')}`, body: messageBody };

          const html = emailBodyToHtml(emailMsg.body, getConfig(tenant, 'business_name', tenant.name || 'Our Team'));
          emailResult = await sendEmail(lead.email, emailMsg.subject, html, {
            tenant,
            replyTo: getConfig(tenant, 'support_email', null) || undefined,
          });

          await db.from('messages').insert({
            tenant_id: tenant.id,
            contact_id: primaryContact?.id || null,
            channel: 'email',
            direction: 'outbound',
            body: emailMsg.body,
            external_id: emailResult?.id || null,
            status: 'sent',
            sent_at: new Date().toISOString()
          });
          try {
            await db.from('conversations').insert({
              tenant_id: tenant.id,
              lead_id: lead.id,
              contact_id: primaryContact?.id || null,
              channel: 'email',
              direction: 'outbound',
              message_body: emailMsg.body,
              metadata: { external_id: emailResult?.id || null, agent: 'follow-up', step: nextStep, max_steps: maxSteps, subject: emailMsg.subject },
            });
          } catch (convErr) {
            log.warn(`conversations insert failed for follow-up email: ${convErr.message}`);
          }
        } catch (emailErr) {
          // Email failure is non-fatal — SMS may have already gone (or not).
          // Don't fail the whole follow-up if Resend has a hiccup.
          log.warn(`Follow-up email failed for ${lead.name}: ${emailErr.message}`);
        }
      }

      // If neither channel actually sent, count as skipped and don't advance the cadence.
      if (!smsResult && !emailResult) {
        skipped++;
        processed.push({ lead_id: lead.id, name: lead.name, action: 'no_channel_succeeded' });
        continue;
      }

      // Advance the drip stage on the contact (always exists at this point)
      await db.from('contacts')
        .update({
          drip_stage: nextStep,
          last_contacted_at: new Date().toISOString(),
          updated_at: new Date().toISOString()
        })
        .eq('id', primaryContact.id)
        .eq('tenant_id', tenant.id);

      // Record idempotency
      await recordIdempotency(tenant.id, idempKey, 'follow_up_sent', {
        step: nextStep,
        message_sid: smsResult?.sid || null,
        email_id: emailResult?.id || null,
      });

      sent++;
      processed.push({
        lead_id: lead.id,
        name: lead.name,
        action: 'sent',
        step: nextStep,
        channels: [smsResult ? 'sms' : null, emailResult ? 'email' : null].filter(Boolean),
        message_sid: smsResult?.sid || null,
        email_id: emailResult?.id || null,
      });

      log.success(`Follow-up step ${nextStep} sent to ${lead.name}`);
    } catch (err) {
      log.error(`Follow-up failed for ${lead.name}`, err);
      errors.push({ lead_id: lead.id, name: lead.name, error: err.message });
    }
  }

  const result = {
    success: true,
    sent,
    skipped,
    processed,
    errors,
    ...(capInfo ? { sms_cap_reached: true, cap: capInfo.cap, count: capInfo.count } : {})
  };
  log.success('Follow-up run completed', { sent, skipped, cap_reached: capReached });
  return result;
}

module.exports = run;
